hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/StackDugum.o -c ./src/StackDugum.cpp
	g++ -I ./include/ -o ./lib/Stack.o -c ./src/Stack.cpp
	g++ -I ./include/ -o ./lib/ListeGezici.o -c ./src/ListeGezici.cpp
	g++ -I ./include/ -o ./lib/CiftYonluDBagilListe.o -c ./src/CiftYonluDBagilListe.cpp
	g++ -I ./include/ -o ./lib/Yonetim.o -c ./src/Yonetim.cpp
	
	
	
	
	g++ -I ./include/ -o ./bin/Test  ./lib/Dugum.o ./lib/StackDugum.o ./lib/Stack.o ./lib/ListeGezici.o ./lib/CiftYonluDBagilListe.o ./lib/Yonetim.o ./src/Test.cpp

	
calistir:
	./bin/Test