hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/BinarySearchTree.o -c ./src/BinarySearchTree.cpp
	g++ -I ./include/ -o ./lib/AgacDugum.o -c ./src/AgacDugum.cpp
	g++ -I ./include/ -o ./lib/AgacBinarySearchTree.o -c ./src/AgacBinarySearchTree.cpp
	g++ -I ./include/ -o ./lib/Yonetim.o -c ./src/Yonetim.cpp
	
	
	
	
	g++ -I ./include/ -o ./bin/Test  ./lib/Dugum.o ./lib/BinarySearchTree.o ./lib/AgacDugum.o ./lib/AgacBinarySearchTree.o ./lib/Yonetim.o ./src/Test.cpp

	
calistir:
	./bin/Test